version: "3"
services:
  gourmandapi:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./:/gourmandapi
    environment:
      - NAME=Ronald_staging
      - GOURMAND_ENV=staging
    entrypoint: ["./docker_commands.sh"]
    networks:
      - g-api-network
  postgres:
    image: postgres:14
    env_file:
      - ./.env
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=pg_oltp_api_password
      - POSTGRES_DB=pg_oltp_api_db_test
    volumes:
      - gourmandapi-docker-db:/var/lib/postgresql/data
    networks:
      - g-api-network
  redis:
    image: redis
    volumes:
      - gourmandapi-redis-db:/data
    ports:
      - 6379:6379
    networks:
      - g-api-network

volumes:
  gourmandapi-docker-db:
  gourmandapi-redis-db:
networks:
  g-api-network:
    external: true
secrets:
  POSTGRES_PASSWORD:
    file: p_pass.txt
  POSTGRES_DB:
    file: p_db.txt
