begin transaction;
truncate  "_Production".review cascade ;
truncate  "_Production".event cascade;
truncate  "_Production".businesstransactionbridge cascade ;
truncate  "_Production".businessholding cascade ;
truncate  "_Production".businesscategorybridge cascade ;
truncate  "_Production".countygrowth cascade;
truncate  "_Production".business cascade;
truncate "_Production".businesscategory cascade;
truncate "_Production".city cascade;
truncate "_Production".county cascade;
truncate "_Production".eventcategory cascade;
truncate "_Production".paymentlevel cascade;
truncate "_Production".state cascade;
truncate "_Production".country cascade;
truncate "_Production".transactiontype cascade;
truncate "_Production".user cascade;
truncate "_Production".authuser cascade;
commit transaction ;