"""role creation

Revision ID: 4a0ad5570d42
Revises: c8cdc2770046
Create Date: 2023-11-01 22:34:52.164955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a0ad5570d42'
down_revision = 'c8cdc2770046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name'),
    schema='_Production'
    )
    op.create_index('ix_role_default', 'role', ['default'], unique=False, schema='_Production')
    op.add_column('authuser', sa.Column('role_id', sa.Integer(), nullable=True), schema='_Production')
    op.alter_column('authuser', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(precision=6),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='_Production')
    op.create_foreign_key(None, 'authuser', 'role', ['role_id'], ['role_id'], source_schema='_Production', referent_schema='_Production')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(None, 'authuser', schema='_Production', type_='foreignkey')
    op.alter_column('authuser', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=6),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='_Production')
    op.drop_column('authuser', 'role_id', schema='_Production')
    op.drop_index('ix_role_default', table_name='role', schema='_Production')
    op.drop_table('role', schema='_Production')
    # ### end Alembic commands ###
