"""empty message

Revision ID: 56470f309b5f
Revises: 6a630cb0012e
Create Date: 2023-10-12 02:58:14.414267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56470f309b5f'
down_revision = '6a630cb0012e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authuser',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email'),
    schema='_Production'
    )
    op.create_table('business',
    sa.Column('businessid', sa.Integer(), nullable=False),
    sa.Column('businessname', sa.String(), nullable=False),
    sa.Column('chainname', sa.String(), nullable=False),
    sa.Column('addressline1', sa.String(), nullable=False),
    sa.Column('addressline2', sa.String(), nullable=True),
    sa.Column('addressline3', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('businessphone', sa.String(), nullable=True),
    sa.Column('businessurl', sa.String(length=500), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('distancetocounty', sa.Integer(), nullable=True),
    sa.Column('cityid', sa.Integer(), nullable=True),
    sa.Column('countyid', sa.Integer(), nullable=True),
    sa.Column('stateid', sa.Integer(), nullable=True),
    sa.Column('paymentlevelid', sa.Integer(), nullable=True),
    sa.Column('lasteditedwhen', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('businessid'),
    schema='_Production'
    )
    op.create_table('businessholding',
    sa.Column('businessholdingid', sa.Integer(), nullable=False),
    sa.Column('businessid', sa.Integer(), nullable=False),
    sa.Column('businessrating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('reviewcount', sa.Integer(), nullable=True),
    sa.Column('closedate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['businessid'], ['_Production.business.businessid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('businessholdingid'),
    schema='_Production'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('businessholding', schema='_Production')
    op.drop_table('business', schema='_Production')
    op.drop_table('authuser', schema='_Production')
    # ### end Alembic commands ###
